# Generated by Django 4.2.18 on 2025-04-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='rentservice.tag'),
        ),
    ]
