# Generated by Django 4.2.18 on 2025-03-27 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
