# Generated by Django 4.2.18 on 2025-04-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentservice', '0002_tag_item_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='collections',
        ),
        migrations.AlterField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='collections', to='rentservice.item'),
        ),
    ]
