# Generated by Django 4.2.18 on 2025-04-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentservice', '0002_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visible_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
