# Generated by Django 4.2.18 on 2025-04-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentservice', '0003_remove_item_collections_alter_collection_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowrequest',
            old_name='timestamp',
            new_name='request_date',
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
