# Generated by Django 4.2.18 on 2025-04-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentservice', '0003_profile_visible_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
