# Generated by Django 4.2.18 on 2025-03-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentservice', '0003_remove_user_google_account_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
