# Generated by Django 4.2.18 on 2025-03-31 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rentservice", "0004_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
