# Generated by Django 4.2.18 on 2025-04-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentservice', '0004_collection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
