# Generated by Django 4.2.18 on 2025-04-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentservice', '0005_collection_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowrequest',
            old_name='request_date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='status',
        ),
    ]
