# Generated by Django 4.2.18 on 2025-04-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentservice", "0005_alter_collection_slug"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="borrowrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_complete", False)),
                fields=("user", "item"),
                name="unique_active_borrow_request",
            ),
        ),
    ]
