# Generated by Django 4.2.18 on 2025-04-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentservice', '0006_rename_request_date_borrowrequest_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowrequest',
            unique_together={('user', 'item')},
        ),
    ]
