# Generated by Django 4.2.18 on 2025-04-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentservice', '0008_rename_timestamp_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined'), ('returned', 'Returned')], default='requested', max_length=20),
        ),
    ]
