# Generated by Django 4.2.18 on 2025-04-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentservice', '0009_borrowrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='borrowed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='borrowed_condition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='returned_condition',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
