# Generated by Django 4.2.18 on 2025-04-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentservice', '0010_borrowrequest_borrowed_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
